version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=your_vector_database_url
    depends_on:
      - vector_db

  vector_db:
    image: your_vector_database_image
    ports:
      - "your_vector_db_port:your_vector_db_port"
    environment:
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    driver: bridge